### ISSUE TITLE
Is there any way to get rid of the ''iconv" dependency?

### ISSUE THREAD

**Issue by grossjonas** [dm77/ZBarScanner#12]
One zbar.jar would be much easier to maintain, when embedding your solution in new android studio projects. So it would be nice to only have the jar and your classes.

Is there any possibility to just use the jar and your classes or even to pack your classes and the zbar.jar in one *.jar-File?

**Comment by dm77** [comment]
Hi @grossjonas. Thanks for checking in. I agree with you about the simplicity in having one single jar. But 
unfortunately zbar being an NDK project it probably isn't possible to package it up as a single jar (correct me if I am wrong).

All this library project does is include the ZBar SDK provided here: http://sourceforge.net/projects/zbar/files/AndroidSDK/

So you might have better luck checking with the guys who made the SDK. Its been over a year (the last update being 2012-04-23) since I saw any updates to the SDK, so I am not sure if you are going to get any help on this. Good luck!

**Comment by grossjonas** [comment]
Thx for answer. I see the point. I'll try that TUIT. Thanks for taking the time.
